spring:
  datasource:
    url: jdbc:mysql://localhost:3306/performance
    username: root
    password: abcd1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api